name: Bump version and release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Build
        run: npm ci && npm run deploy
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          preset: conventionalcommits
      - name: Publish to npm
        uses: pascalgn/npm-publish-action@1.3.3
        with:
          workspace: 'dist'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
