name: Bump version and release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Build
        run: npm ci && npm run deploy
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          preset: conventionalcommits
      - name: npm publish && cd dist
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
