- name: Conventional Changelog Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: TriPSs/conventional-changelog-action@v3.4.0
      - with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
