name: Conventional Changelog Action

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Build
        run: npm ci
        run: npm deploy
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          preset: conventionalcommits
      - name: npm publish
        uses: JS-DevTools/npm-publish@v1
