on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
